import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TeamSwitcher from "./dashboard/components/team-switcher";
import { MainNav } from "./dashboard/components/main-nav";
import { Search } from "./dashboard/components/search";
import { UserNav } from "./dashboard/components/user-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
      <div className="border-b">
          <div className="flex h-16 items-center px-4">
            <TeamSwitcher />
            <MainNav className="mx-6" />
            <div className="ml-auto flex items-center space-x-4">
              <Search />
              <UserNav />
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
